### ISSUE TITLE
Expand tests on the Fortran interface

### ISSUE THREAD

**Issue by mkstoyanov** [ORNL/TASMANIAN#1]
Increase Fortran coverage of the Tasmanian tests!

**Comment by mkstoyanov** [comment]
* Fortran testing has been greatly expanded, the Fortran 90/95 module is mostly-stable now. 
* Need to expand the coverage, some I/O or more exotic cases need to be tested as well

**Comment by mkstoyanov** [comment]
* I/O is tested, both single-node and MPI
* remains update-grid and some of the static methods

**Comment by diogosampaiolima** [comment]
Hi. Don't know if this is the right place to ask, but here it goes.

I am unable to run "fortester.f90" or "example_sparse_grids.f90".

I use Ubuntu and when trying to run "fortester90.out" says "no such file or directory"

Doing "chmod -x fortester90.out" and trying to run it again, it says "cannot execute binary file: Exec format error".

**Comment by mkstoyanov** [comment]
@diogosampaiolima How did you build Tasmanian?
Using CMake you need `-D Tasmanian_ENABLE_FORTRAN=ON`
Using the `install` script you need `-fortran`
Using GNU Make you need `make fortran`

**Comment by mkstoyanov** [comment]
Fortran coverage is now at acceptable level.
