### ISSUE TITLE
Create a pip installer

### ISSUE THREAD

**Issue by mkstoyanov** [ORNL/TASMANIAN#418]
* create a pip-installer for Tasmanian
* very appropriate given the expanded Python capabilities

**Comment by mkstoyanov** [comment]
Figured out how to create off-line installer. The on-line installer works under `docker` (ubuntu) but does not agree with main Ubuntu or MacOSX.

See:
https://github.com/mkstoyanov/TASMANIAN/tree/pip_installer/PythonPipInstaller

**Comment by mkstoyanov** [comment]
@dalg24 Can you try it on your Mac.

**Comment by mkstoyanov** [comment]
Added the pip installer for version 7.0

https://pypi.org/project/Tasmanian/

**Comment by dalg24** [comment]
```
pip3 show Tasmanian
Name: Tasmanian
Version: 7.0
Summary: UQ library for sparse grids and Bayesian inference
Home-page: https://tasmanian.ornl.gov
Author: Miroslav Stoyanov
Author-email: stoyanovmk@ornl.gov
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires:
```

**Comment by dalg24** [comment]
* License shows as unknown.
* IMO we need a requirement file, even if we only put numpy in it

**Comment by dalg24** [comment]
Also I was initially surprised about the installation prefix and wondered if it should go to `<prefix>/lib/pythonX.Y/dist-packages/Tasmanian` instead but I think you did the right thing.

**Comment by mkstoyanov** [comment]
@dalg24 the current installer can use improvement, but I didn't want to delay the release any longer. I have looked at all of the above issues:

* The installation should have been done with:
```
python3 -m pip install Tasmanain --user
```
in which case the install folder would be `prefix = /home/me/.local/` then things go into `lib`, `bin` and `lib/pythonX.Y/site-packages/` ...
* I don't think the the installation in `/usr/local/` is working right now, try:
```
import Tasmanian
grid = Tasmanian.makeWaveletGrid(2, 1, 1) # this should give an error
print(Tasmanian.__version__)  # this is also an error
```
* The current install covers the cases of `--user` and python virtual environment only.
* The install process builds in a temp folder, then installs in another temp folder, then moves everything to the final location ... the move messes things big time. I have to know the final location beforehand so that libraries and modules can find each other.
* PIP only accepts a very short list of licenses, I cannot put `3-clause BSD` in there. It is better to write `UNKNOWN` in which case the user can see the home-page or github, rather than writing the wrong license and creating a legal ambiguity.
* The project comes with `pyproject.toml` file that lists the dependencies, but it doesn't work for some reason. The standard way to set dependencies is to use the setup-script, but since we are compiling (as opposed to just downloading script files) the `scikit-build`, `packaging` and `numpy` dependencies must be installed before we invoke the setup script.
