### ISSUE TITLE
Deploy Tasmanian sparse surrogates within Thornado

### ISSUE THREAD

**Issue by mkstoyanov** [ORNL/TASMANIAN#434]
Keep this issue active to document any problems or changes to Tasmanian necessitated by the Tornado interface.

**Comment by mtlaiu** [comment]
Compressed four 4-D opacity tables used in neutrino transport to given tolerances (Python interface).

**Comment by mtlaiu** [comment]
Wrote a python routine to test the compressed tables with several error measurements.

**Comment by mtlaiu** [comment]
Modified Makefiles in Thornade to include/link Tasmanian. No changes needed on the Tasmanian side.

**Comment by mkstoyanov** [comment]
Good news, @mtlaiu 
Which version did you use? Release 7.0 or Development 7.1?

* We should work up a simple regression test and add it to Tasmanian nightly.
* We should suggest that Tornado does the same.

**Comment by mtlaiu** [comment]
I am using Development 7.1 and testing with the examples in example_sparse_grids.f90

**Comment by mtlaiu** [comment]
- Wrote new routine in Thornado to take compressed opacity tables from Tasmanian. 
- Tested interpolation accuracy in an integral norm in Thornado.
- Investigating new scaling for each opacity table to improve the compression rate and accuracy. Possible approaches including leveraging symmetry in the tables, shifting and scaling the tabulated quantities in both linear and logarithmic scales.

**Comment by mtlaiu** [comment]
- Plotted the histograms of each tabulated quantities. 
- Experimenting the compression of NES opacity kernels using various scales, with or without the symmetric property imposed. It's expected that imposing the symmetry before compression could reduce the variation in the tabulated quantities thus improve compression rate and accuracy.

**Comment by mtlaiu** [comment]
- Debugging issues in low resolution opacity tables.
- Testing compression on high resolution opacity tables.
- Quantifying the difference between the compressed high resolution tables and the low resolution tables.
- Creating simple transport testbeds for compressed opacities.
