### ISSUE TITLE
Avoid negative interpolated values

### ISSUE THREAD

**Issue by MariusCausemann** [ORNL/TASMANIAN#486]
Hi,
I'm using Tasmanian to construct a model of a function with high dimensional input (d=3 to 10)  and 
compute interpolated values. Since my function has a sharp interface, I apply a local polynomial grid of order 1 and spatial refinement (refine_fds / refine_parents_first for stability). Even though the function output is always positive, I get negative interpolated values. Is there a way to avoid negative interpolated values (other than just cropping them)?
Thanks!

**Comment by mkstoyanov** [comment]
The short answer is unfortunately a NO!

The longer explanation is that even though the full tensor piecewise linear interpolation guarantees that the interpolant will fall in the convex hull of the input data, the multi-dimensional construction uses a weighted superposition of tensors and some of the weights are guaranteed to be negative. The effect is observed in other respects, such as negative sparse grid quadrature weights even when using global rules with only positive 1-D weights.

However, note that the error estimates for multidimensional interpolation still hold, i.e., when you refine the grid, eventually all values will fall back into the positive range. The negative values are due entirely on interpolation error and the fact that the grid is too coarse in some regions. Thus, cropping the values is a perfectly reasonable strategy.

**Comment by MariusCausemann** [comment]
Thank you very much for your fast and detailed answer!
