### ISSUE TITLE
Use gfortran on Mac OSX

### ISSUE THREAD

**Issue by zz273** [ORNL/TASMANIAN#487]
Hi Miroslav and all,

I have asked a [question](https://github.com/ORNL/TASMANIAN/issues/476) about using the Fortran interface on Mac OSX. And I learned that it's better to Cmake instead of gfortran to run the code because Cmake can correctly link to `libstdc++`.

But still, I was wondering whether there is any possibility to use gfortran? The reason is that I also want to link to other libraries except for TASMANINA. Specifically, I am using the following code to use an optimization package named IPOPT:

`gfortran hs071.f90 -o hs071.out -L /usr/local/lib -lipopt -fbounds-check -O2
`

I search for using Cmake to link to this package, but it seems complicated for me. Hopefully, I can use gfortran for both packages. If gofrtran is not desirable, I also have ifort.

Any advice is appreciated. Thanks!

**Comment by mkstoyanov** [comment]
Every compiler requires it's own flags and options and linking to multiple libraries can get rather hectic. Tasmanian can have a long and complicated list of dependencies, depending on which options were used during build, manually using all this is a nightmare.

The purpose of CMake is to simplify all of that:
```
project(zz273 VERSION 0.1 LANGUAGES Fortran)
find_package(Tasmanian 7.0 PATH <enter-path> REQUIRED FORTRAN)

add_executable(hs071 hs-71.f90)
target_link_libraries(hs071 Tasmanian::Fortran)
target_link_libraries(hs071 ipopt)
target_include_directories(hs071 PUBLIC /usr/local/lib)
target_compile_options(hs071 PRIVATE -fbounds-check -O2)
```
Call this with
```
mkdir build
cd build
cmake -DCMAKE_Fortran_COMPILER=gfortran ..
```
Then type `make VERBOSE=1` and you will see the actual commands that will get executed. Also note that the command will be different on each system and each set of  Tasmanian options.

**Comment by zz273** [comment]
Hi Miroslav,

Thank you very much for your reply. Everything works well. CMake does be very powerful! I should definitely learn more about that.

Thank you!

**Comment by mkstoyanov** [comment]
Yes, CMake makes life much easier when you have to build against a project with unknown set of dependencies, and all other compiler flags and options can be added with the appropriate commands. You can even write if-statements to check compiler brands (ifort vs gfortran), for loops to cycle over all options, and so on.

Glad things work now.
