### ISSUE TITLE
Extrapolation rule for hierarchical interpolation

### ISSUE THREAD

**Issue by zz273** [ORNL/TASMANIAN#501]
Hi Miroslav and all,

I am using the  'Local Polynomial Grids: Hierarchical interpolation' to apply the adaptive sparse grid method.

I need to maximize the interpolation function and should get some values out of the range of interpolation. But I did not find the extrapolation rule in the manual. Could you give me so advice on that? Thanks a lot!

**Comment by mkstoyanov** [comment]
I don't think I understand the question. Tasmanian does interpolation on a hypercube domain, never extrapolation. In fact, I don't think extrapolation in this context is a valid math technique when using polynomial or piecewise polynomial basis.

**Comment by zz273** [comment]
Hi Miroslav,

Thank you for your reply. I see. You are right. It seems like doing extrapolation is not a good idea. 

Just to make sure. Even if Tasmania returns evaluation out of the domain,  we still cannot use it?

**Comment by mkstoyanov** [comment]
In the local polynomial and wavelet cases, giving input that is outside of the domain is `undefined behavior`. For performance reasons, Tasmanian does not check if points are inside and I does not attempt to produce anything meaningful. Performance takes precedence over trying to solve a mathematically ill-posed problem.

**Comment by zz273** [comment]
I see. Thanks!

**Comment by mkstoyanov** [comment]
No problem!
