### ISSUE TITLE
OSError when Tasmanian is imported

### ISSUE THREAD

**Issue by coffeemelody** [ORNL/TASMANIAN#547]
Hello,

I installed with Python Pip and it installed successfully. I mainly want to use the library with Jupyter notebook. However I couldn't import the library and it shows the following error message:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-a4c10f140fa8> in <module>
      1 import numpy as np
----> 2 import Tasmanian
      3 from scipy import interpolate
      4 from scipy.stats import truncnorm
      5 from scipy.optimize import fsolve

~/anaconda3/lib/python3.7/site-packages/Tasmanian.py in <module>
     41 SparseGrid = TasmanianSparseGrid
     42 
---> 43 import TasmanianDREAM as DREAM
     44 
     45 from TasmanianAddons import *

~/anaconda3/lib/python3.7/site-packages/TasmanianDREAM.py in <module>
     29 ##############################################################################################################################################################################
     30 
---> 31 from TasmanianDreamLikely import *
     32 from TasmanianDreamSampler import *
     33 from TasmanianDreamState import DreamState as State

~/anaconda3/lib/python3.7/site-packages/TasmanianDreamLikely.py in <module>
     36 from TasmanianConfig import TasmanianInputError as InputError
     37 
---> 38 pLibDTSG = cdll.LoadLibrary(__path_libdream__)
     39 
     40 pLibDTSG.tsgGetNumOutputs.restype = c_int

~/anaconda3/lib/python3.7/ctypes/__init__.py in LoadLibrary(self, name)
    432 
    433     def LoadLibrary(self, name):
--> 434         return self._dlltype(name)
    435 
    436 cdll = LibraryLoader(CDLL)

~/anaconda3/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: /home/qingsong/.local/lib/libtasmaniandream.so: cannot open shared object file: No such file or directory

--------------------------------------------------------------------------------------------------------------------------end of error message

I am using ubuntu. Thanks!

**Comment by mkstoyanov** [comment]
Looks like it didn't install correctly, it says that `/home/qingsong/.local/lib/libtasmaniandream.so` is missing. There should be several tasmanian libraries in `/home/qingsong/.local/lib/`

I have seen this when I forget to add the `--user` to the pip install.
```
python3 -m pip install Tasmanian --user
```
But note that this will not work now, since you have to delete the current PIP cache in `/home/qingsong/.cache/<pip something>`

You don't need the `--user` when working in a `venv` environment, but you need it otherwise.

**Comment by coffeemelody** [comment]
Thanks for your prompt reply and I tried 'pip uninstall Tasmanian' and then 'pip install' again with '--user'. Now I can import without any error. I did try to delete the current PIP cache but I didn't find a correct way to do it.

**Comment by mkstoyanov** [comment]
@coffeemelody I'm glad things worked out.

Deleting the PIP cache is necessary to force the project to recompile, but I guess it wasn't needed in your case.

Best!
