### ISSUE TITLE
a simple question about installation

### ISSUE THREAD

**Issue by btwbtm** [ORNL/TASMANIAN#657]
Hi. I am using windows system and want use this package as a component of matlab project as in https://github.com/agoupy/eigenvalue_gPC. I am unfamiliar with cmake. So I hope to know if the pip installation way also works in my case, or using pip means I have to use python rather than matlab? Thx!

**Comment by mkstoyanov** [comment]
You can enable the MATLAB interface through PIP by setting the environment variable `Tasmanian_MATLAB_WORK_FOLDER` to a valid folder, but PIP sometimes struggles with newer versions of the MS Visual Studio Compiler. You can give it a shot, but CMake is probably the better option.

Using the CMake GUI is not hard on windows, just follow the instruction on the Tasmanan documentation page.

**Comment by mkstoyanov** [comment]
I'm closing this one, reopen if needed.
