### ISSUE TITLE
Scale Correction in Fortran?

### ISSUE THREAD

**Issue by ckrausecon** [ORNL/TASMANIAN#681]
Dear Miroslav,

It seems to me that, unless in Python, there is no possibility for scale correction in Fortran's local refinement procedure. Is that true? And if yes, do you plan to include scale correction at some point in time? 

(Sorry in case this question was already asked.)

Best
Christopher

**Comment by mkstoyanov** [comment]
Which version of Fortran are you using? Scale correction should work fine in the 2003 OOP interface.

The older 90/95 interface required a lot of manual work and it was too hard to maintain. Much of the functionality has not been ported and in more ways than not, the old interface is deprecated.

The new interface uses automatic generation for the bindings and it is much easier to maintain harder things like many default parameters passed into a function.

**Comment by mkstoyanov** [comment]
Swig is the way to go, the interface is much closer to C++/Python and thus easier to maintain and document, and the interface does not require SWIG being installed or enabled. In fact, if you build Tasmanian with Fortrain 90/95, then 2003 is already installed.
