### ISSUE TITLE
Tasmanian+rocm testing build fails on frontier 

### ISSUE THREAD

**Issue by wspear** [ORNL/TASMANIAN#742]
I'm testing Tasmanian built with spack on Frontier for E4S validation using the following spec:
Edit: (Targeting frontier, these results are actually from crusher)
```
-- linux-sles15-zen3 / gcc@11.2.0 -------------------------------
nopqpbc tasmanian@7.9~blas~cuda~fortran~ipo~magma+mpi~openmp~python+rocm~xsdkflags amdgpu_target=gfx90a build_system=cmake build_type=Release
7o5iua6     cmake@3.25.2~doc+ncurses+ownlibs~qt build_system=generic build_type=Release
igbrz2c         ncurses@6.3~symlinks+termlib abi=none build_system=autotools
savxweu             pkgconf@1.8.0 build_system=autotools
gv7ah47         openssl@1.1.1-os~docs~shared build_system=generic certs=mozilla
vw5wbnb     cray-mpich@8.1.23+wrappers build_system=generic
5fmb57z     hip@5.4.0~cuda~ipo+rocm build_system=cmake build_type=Release patches=ca523f1
euzfcae     hsa-rocr-dev@5.4.0+image~ipo+shared build_system=cmake build_type=Release patches=71e6851
z5r2sar     llvm-amdgpu@5.4.0~ipo~link_llvm_dylib~llvm_dylib~openmp+rocm-device-libs build_system=cmake build_type=Release patches=a08bbe1
x4yi2g3     rocblas@5.4.0~ipo+tensile amdgpu_target=auto build_system=cmake build_type=Release patches=81591d9
cpdjwvl     rocsolver@5.4.0~ipo+optimal amdgpu_target=auto build_system=cmake build_type=Release patches=8067bfb
icwqurs     rocsparse@5.4.0~ipo~test amdgpu_target=auto build_system=cmake build_type=Release
```

I copied the testing directory from <tasmanian root>/share/tasmanian/testing, did `mkdir build;cd build; cmake ..` and that worked but make failed with the error output below. Any advice on how to get this working? I'm happy to dig up any additional diagnostic info that could help.

```
[ 54%] Linking CXX executable example_sparse_grids
Tasmanian Sparse Grids  version: 7.9
                        license: BSD 3-Clause with UT-Battelle disclaimer
          OpenMP multithreading: Disabled
          GPU backend framework: ROCm/HIP
         Available acceleration:  gpu-cublas gpu-cuda
                 Available GPUs:
          0:                     with  65520MB of RAM
          1:                     with  65520MB of RAM

/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/example_sparse_grids.dir/example_sparse_grids_05.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples_cxx/CMakeFiles/example_sparse_grids.dir/build.make:282: examples_cxx/example_sparse_grids] Error 1
make[1]: *** [CMakeFiles/Makefile2:102: examples_cxx/CMakeFiles/example_sparse_grids.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

```

**Comment by wspear** [comment]
It looks like the cmake build definitions are omitting a `-pthread` argument at link time. This is the build command that is failing:
` /opt/cray/pe/gcc/11.2.0/bin/c++ CMakeFiles/example_sparse_grids.dir/example_sparse_grids_01.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_02.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_03.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_04.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_05.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_06.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_07.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_08.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_09.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_10.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids_11.cpp.o CMakeFiles/example_sparse_grids.dir/example_sparse_grids.cpp.o -o example_sparse_grids  -Wl,-rpath,/ccs/home/wspear/csc439-wspear-orion/crusher/23.02/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/tasmanian-7.9-nopqpbcd5n7qw7b5zft2ee5gvzdlzhg7/lib:/opt/rocm-5.4.0/lib:/opt/cray/pe/mpich/8.1.23/ofi/gnu/9.1/lib /ccs/home/wspear/csc439-wspear-orion/crusher/23.02/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/tasmanian-7.9-nopqpbcd5n7qw7b5zft2ee5gvzdlzhg7/lib/libtasmaniandream.so.7.9.0 /ccs/home/wspear/csc439-wspear-orion/crusher/23.02/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/tasmanian-7.9-nopqpbcd5n7qw7b5zft2ee5gvzdlzhg7/lib/libtasmaniansparsegrid.so.7.9.0 /opt/rocm-5.4.0/lib/librocsparse.so.0.1.50400 /opt/rocm-5.4.0/lib/librocsolver.so.0.1.50400 /opt/rocm-5.4.0/lib/librocblas.so.0.1.50400 /opt/rocm-5.4.0/lib/libamdhip64.so.5.4.50400 /opt/rocm-5.4.0/llvm/lib/clang/15.0.0/lib/linux/libclang_rt.builtins-x86_64.a /opt/cray/pe/mpich/8.1.23/ofi/gnu/9.1/lib/libmpi_gnu_91.so `

If I run it directly and add -pthread it builds. I'm not sure if/how I should try to fix the test cmake files to address this. It seems like this could hit non-test use cases.

**Comment by mkstoyanov** [comment]
This is probably related to `~openmp` and I think `+openmp` won't work either because the spack-rocm package interprets openmp as offload (Tasmanian only uses OpenMP for multithreading).

Can you try this on `@develop` since the ROCM build system was updated. `@develop` uses HIP as a CMake language and that will become the official Tasmanian end-of-ECP release.

If it has to be 7.9 then I can make it work next week.

**Comment by wspear** [comment]
@mkstoyanov I'm seeing the same error with tasmanian@develop, both +openmp and ~openmp:

```
[wspear@login2.crusher build]$ make
[  4%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_01.cpp.o
[  8%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_02.cpp.o
[ 12%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_03.cpp.o
[ 16%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_04.cpp.o
[ 20%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_05.cpp.o
[ 25%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_06.cpp.o
[ 29%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_07.cpp.o
[ 33%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_08.cpp.o
[ 37%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_09.cpp.o
[ 41%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_10.cpp.o
[ 45%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids_11.cpp.o
[ 50%] Building CXX object examples_cxx/CMakeFiles/example_sparse_grids.dir/example_sparse_grids.cpp.o
[ 54%] Linking CXX executable example_sparse_grids
Tasmanian Sparse Grids  version: 7.10 (development)
                git commit hash: e62d47ed20b44160ce963263a6fc9000deadb83c
                cmake cxx flags: Release, 
                        license: BSD 3-Clause with UT-Battelle disclaimer
          OpenMP multithreading: Disabled
          GPU backend framework: ROCm/HIP
         Available acceleration:  gpu-cublas gpu-cuda
                 Available GPUs:
          0:                     with  65520MB of RAM
          1:                     with  65520MB of RAM

/usr/bin/ld: CMakeFiles/example_sparse_grids.dir/example_sparse_grids_05.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples_cxx/CMakeFiles/example_sparse_grids.dir/build.make:282: examples_cxx/example_sparse_grids] Error 1
make[1]: *** [CMakeFiles/Makefile2:102: examples_cxx/CMakeFiles/example_sparse_grids.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

```
